/*  Message-number definitions derived from "DIALHOT.MSG"  */

#define NOTREG      1
#define ISDEMO      2
#define REGNOW      3
#define HOTKEYAD    4
#define HKHELP      5
#define HKHLP2      6
#define HKHLP2H     7
#define HKHLPFTR    8
#define INFORMA     9
#define MAIN10     10
#define MAIN10S    11
#define MAINPRM1   12
#define NOSUCH     13
#define NOCHANG    14
#define SETSAVD    15
#define HOTON      16
#define HOTOFF     17
#define NOPKEY     18
#define NOTDEF2    19
#define XCUTING    20
#define PKEYHDR    21
#define PKEYLIN    22
#define PKEYFTR    23
#define CNF12      25
#define CNF21      26
#define CNF30      27
